### ISSUE TITLE
acmetool's HTTP self-test parameters differ from those used by boulder

### ISSUE THREAD

**Issue by skinkie** [hlandau/acme#199]
I am a new user to acmetool, while I am running letsencrypt certificates already. My problem seems to be related to acmetool not writing the challenge file to the setup webroot. Using the tool I receive the following output:

```
sudo acmetool want iepenbierferfier.frl www.iepenbierferfier.frl
20160827000257 [ERROR] acme.storageops: could not obtain authorization for iepenbierferfier.frl: failed all combinations
20160827000257 [ERROR] acme.storageops: Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: failed all combinations
20160827000257 [ERROR] acme.storageops: error while processing targets: the following errors occurred:
error satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20160827000257 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:
error satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20160827000257 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
```

```
acmetool status
Settings:
  ACME_STATE_DIR: /var/lib/acme
  ACME_HOOKS_DIR: /usr/lib/acme/hooks
  Default directory URL: https://acme-v01.api.letsencrypt.org/directory
  Preferred key type: rsa-2048
  Additional webroots:
    /opt/cherokee/var/www/.well-known/acme-challenge

Available accounts:
  Account(acme-v01.api.letsencrypt.org%2fdirectory/a3n2fi3vvxvlkvnehrdaadxildvuhhqsgbgoxq6wihvzsxuggiya)
    thumbprint: wHdGj50hMqTQj2oE7KsqXMxeQ8ofB_4luUyLRiIdZUk

Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0)
  error: Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): no certificate satisfies this target
```

Using a small shell script I am monitoring the webfolder, but it remains empty. I also notice that the challenges itself do come in via the webserver:

```
2001:bc8:3020:300::1 - - [27/Aug/2016:00:02:57 +0200] "GET /.well-known/acme-challenge/1bFyh5fDOAZvX5juOzW7ssDqUbW4UamNN_0eQ8DOs98 HTTP/1.1" 404 672 "http://iepenbierferfier.frl/.well-known/acme-challenge/1bFyh5fDOAZvX5juOzW7ssDqUbW4UamNN_0eQ8DOs98" "Go-http-client/1.1"
```

Any advises what I can do to monitor that the file itself is written... _**somewhere**_?

Additionally I have attempted the proxy configuration, which also didn't complete.

**Comment by hlandau** [comment]
Try running with `--xlog.severity=debug`.

acmetool deletes challenge files after (successful or unsuccessful) use so it's not surprising you can't find them, but debug logging should indicate if there's any problem writing them.

**Comment by skinkie** [comment]
```
20160828115133 [DEBUG] acme.storageops: Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): best certificate satisfying is <nil>, err=Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): no certificate satisfies this target
20160828115133 [DEBUG] acme.storageops: Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): requesting certificate
20160828115133 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/directory
20160828115133 [DEBUG] acme.api: response: &{200 OK 200 HTTP/1.1 1 1 map[Boulder-Request-Id:[GD-gKQ0l7R_aPsVNBwXUHXuIh53K_KsxABPT9dZ_8Zo] Strict-Transport-Security:[max-age=604800] Pragma:[no-cache] Date:[Sun, 28 Aug 2016 09:52:39 GMT] Content-Type:[application/json] Content-Length:[280] Replay-Nonce:[k-1TDQXDKwVDr7a_U3TyNWnk7mWIMEUCF-JaZipU5DI] X-Frame-Options:[DENY] Expires:[Sun, 28 Aug 2016 09:52:39 GMT] Cache-Control:[max-age=0, no-cache, no-store] Connection:[keep-alive] Server:[nginx]] 0xc420238140 280 [] false false map[] 0xc4201ee690 0xc42032e0b0} <nil>
20160828115133 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-reg
20160828115133 [DEBUG] acme.api: response: &{409 Conflict 409 HTTP/1.1 1 1 map[Boulder-Requester:[3651621] Location:[https://acme-v01.api.letsencrypt.org/acme/reg/3651621] Cache-Control:[max-age=0, no-cache, no-store] Content-Length:[107] Content-Type:[application/problem+json] Boulder-Request-Id:[KG1ovWi6xzf-jNkxKV7Ql9XAr39V37baQIlmM977Gq8] Replay-Nonce:[gif3HoQxGm2lHBSK-sc_GErnKd1DloZCTlJLi13wuH0] Expires:[Sun, 28 Aug 2016 09:52:39 GMT] Pragma:[no-cache] Date:[Sun, 28 Aug 2016 09:52:39 GMT] Server:[nginx]] 0xc4202fc1c0 107 [] true false map[] 0xc4200f6d20 0xc42032e0b0} <nil>
20160828115134 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/reg/3651621
20160828115134 [DEBUG] acme.api: response: &{202 Accepted 202 HTTP/1.1 1 1 map[Server:[nginx] Boulder-Request-Id:[fz0MFL_Zkbx2JBkl3BtnC3sN7mrXmsdDfxjJ10SCQB4] Boulder-Requester:[3651621] Expires:[Sun, 28 Aug 2016 09:52:39 GMT] Cache-Control:[max-age=0, no-cache, no-store] Pragma:[no-cache] Connection:[keep-alive] Content-Type:[application/json] Content-Length:[635] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-authz>;rel="next" <https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf>;rel="terms-of-service"] Replay-Nonce:[nQx9a2lrJxEy5YCYjD7aCTpq_IeJwBK69eDS9krZLVY] Date:[Sun, 28 Aug 2016 09:52:39 GMT]] 0xc4202fc280 635 [] false false map[] 0xc4200f73b0 0xc4200c3b80} <nil>
20160828115134 [DEBUG] acme.storageops: trying to obtain authorization for "www.iepenbierferfier.frl"
20160828115134 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-authz
20160828115134 [DEBUG] acme.api: response: &{201 Created 201 HTTP/1.1 1 1 map[Content-Type:[application/json] Replay-Nonce:[R-ujOyu3wCx1iCc73Scx3_DDxCwJBu3X2MbXnuEdaQk] Strict-Transport-Security:[max-age=604800] Pragma:[no-cache] Server:[nginx] Boulder-Request-Id:[VrLJUofxUL05MBhURPY9j8LubwH20oJgfahW0zttcIg] Content-Length:[1008] Location:[https://acme-v01.api.letsencrypt.org/acme/authz/VaZS6XGiZ3yC4lY8kti-AfVSKEpiicDKYJOVQzcK4Eg] Cache-Control:[max-age=0, no-cache, no-store] Date:[Sun, 28 Aug 2016 09:52:40 GMT] Connection:[keep-alive] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"] X-Frame-Options:[DENY] Expires:[Sun, 28 Aug 2016 09:52:40 GMT] Boulder-Requester:[3651621]] 0xc4203a0100 1008 [] false false map[] 0xc4201ee1e0 0xc4200c3b80} <nil>
20160828115134 [DEBUG] acme.solver: attempting challenge type tls-sni-01
20160828115134 [DEBUG] acme.responder: failed to start TLS-SNI listener: listen tcp :443: bind: address already in use
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/haproxy
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/reload
20160828115134 [DEBUG] acme.responder: tls-sni-01 self-test failed: when doing self-test, got 2 certificates, expected 1
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/haproxy
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/reload
20160828115134 [DEBUG] acme.solver: challenge start failed: when doing self-test, got 2 certificates, expected 1
20160828115134 [DEBUG] acme.solver: attempting challenge type http-01
20160828115134 [DEBUG] acme.responder: failed to listen on [::]:80: listen tcp [::]:80: bind: address already in use
20160828115134 [DEBUG] acme.responder: failed to listen on :80: listen tcp :80: bind: address already in use
20160828115134 [DEBUG] acme.responder: listening on [::1]:4402
20160828115134 [DEBUG] acme.responder: listening on 127.0.0.1:4402
20160828115134 [DEBUG] acme.responder: listening on [::1]:402
20160828115134 [DEBUG] acme.responder: listening on 127.0.0.1:402
20160828115134 [DEBUG] acme.responder: writing 2 webroot challenge files
20160828115134 [DEBUG] acme.responder: writing webroot file /opt/cherokee/var/www/.well-known/acme-challenge/oJCk0rvzdnCSBnwDbDajBxi0rI5uuguxbB5nsR5IrJM
20160828115134 [DEBUG] acme.responder: writing webroot file /var/run/acme/acme-challenge/oJCk0rvzdnCSBnwDbDajBxi0rI5uuguxbB5nsR5IrJM
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/haproxy
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/reload
20160828115134 [DEBUG] acme.responder: http-01 self test
20160828115134 [INFO] acme.responder: http-01 self test failed: Get https://www.iepenbierferfier.frl/.well-known/acme-challenge/oJCk0rvzdnCSBnwDbDajBxi0rI5uuguxbB5nsR5IrJM: x509: certificate is valid for iepenbierferfier.frl, iepenbierferfier.nl, not www.iepenbierferfier.frl
20160828115134 [DEBUG] acme.responder: removing webroot file /opt/cherokee/var/www/.well-known/acme-challenge/oJCk0rvzdnCSBnwDbDajBxi0rI5uuguxbB5nsR5IrJM
20160828115134 [DEBUG] acme.responder: removing webroot file /var/run/acme/acme-challenge/oJCk0rvzdnCSBnwDbDajBxi0rI5uuguxbB5nsR5IrJM
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/haproxy
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/reload
20160828115134 [DEBUG] acme.solver: challenge start failed: Get https://www.iepenbierferfier.frl/.well-known/acme-challenge/oJCk0rvzdnCSBnwDbDajBxi0rI5uuguxbB5nsR5IrJM: x509: certificate is valid for iepenbierferfier.frl, iepenbierferfier.nl, not www.iepenbierferfier.frl
20160828115134 [DEBUG] acme.solver: attempting challenge type dns-01
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/haproxy
20160828115134 [DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/reload
20160828115134 [DEBUG] acme.solver: challenge start failed: could not install DNS challenge, no hooks succeeded
20160828115134 [ERROR] acme.storageops: could not obtain authorization for www.iepenbierferfier.frl: failed all combinations
20160828115134 [ERROR] acme.storageops: Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: failed all combinations
20160828115134 [DEBUG] acme.storageops: done processing targets, reconciliation complete, 1 errors occurred
20160828115134 [ERROR] acme.storageops: error while processing targets: the following errors occurred:
error satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20160828115134 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:
error satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20160828115134 [DEBUG] acme.storageops: disjoint hostname mapping: iepenbierferfier.frl -> Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0)
20160828115134 [DEBUG] acme.storageops: disjoint hostname mapping: www.iepenbierferfier.frl -> Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0)
20160828115134 [DEBUG] acme.storageops: could not find certificate satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): no certificate satisfies this target
20160828115134 [DEBUG] acme.storageops: could not find certificate satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): no certificate satisfies this target
20160828115134 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying Target(iepenbierferfier.frl,www.iepenbierferfier.frl;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
```

**Comment by WayneD** [comment]
acmetool tries the web request itself to make sure that it works before using the API, and it is that self-test that is failing. I'd suggest manually creating the file it mentions (down in /opt) and then trying a manual curl request from the acme host and see what sort of an error you get. You might have an issue with internal routing to the public domain, or the webserver might have some kind of permissions issue accessing the file.

**Comment by skinkie** [comment]
It looks pretty clear to me that a HSTS set up webserver running a new domain where no certificate has been issued for yet, is blocked because the certificate is invalid... chicken/egg.

**Comment by hlandau** [comment]
The problem here is that you're redirecting `http://example.com/.well-known/acme-challenge/...` to `https://example.com/.well-known/acme-challenge/...`, which has an invalid certificate. Fairly sure Let's Encrypt wouldn't validate that either, so the self-test failing is correct here. You should exempt `/.well-known/acme-challenge/` URLs from the HTTP-to-HTTPS redirect.

STS has nothing to do with this, that's a browser-side mechanism which acmetool doesn't follow.

**Comment by skinkie** [comment]
So consider that I want to renew a certificate which is **expired**, and HTST is set up at the webserver. Would acmetool or letsencrypt to change my configuration because I want to renew a certificate? The check is there to validate that I own the domainname, not to test if I am using expired or self-signed certificates.

**Comment by hlandau** [comment]
Huh?

HSTS is irrelevant. acmetool doesn't implement `Strict-Transport-Security`. Let's Encrypt doesn't implement `Strict-Transport-Security`. Use of the `Strict-Transport-Security` header is completely independent of redirecting HTTP requests to HTTPS requests.

You can't complete the challenge because `http://example.com/.well-known/acme-challenge/...` is not retrievable.

**Comment by skinkie** [comment]
Probably because the webserver redirects the tool to https://... which is 
ignored because of the expired certificate?

**Comment by hlandau** [comment]
Don't redirect the tool to `https://`.

**Comment by skinkie** [comment]
This is implicit behavior for a HTST site. I can't disable this behavior for anything in the domain.

**Comment by hlandau** [comment]
There is no such thing as an "HTST" [sic] site or "HSTS" site. You are conflating two separate issues: issuance of the `Strict-Transport-Security` header and auto-redirect to HTTPS. These are two entirely separate things and nothing whatsoever in any RFC forces these to be combined. Whatever issue you face here is a limitation in your webserver, and is out-of-scope as a problem for the purposes of acmetool. You should file an issue with the appropriate project.

**Comment by skinkie** [comment]
Hence this confirms that acmetool does not validate the _domain_, but the _webserver_ configuration. One way or the other, if acmetool can't validate an auto-redirect for a _valid_ HTTPS site, that is a bug too. You can ignore the issue, but you are at least now made aware of it.

**Comment by hlandau** [comment]
If acmetool doesn't pass the configuration Let's Encrypt isn't going to either.

**Comment by skinkie** [comment]
I'm happy to validate that if I had a tool that wrote a challenge file to the webroot. And opened an issue upstream as well: https://community.letsencrypt.org/t/validation-of-an-expired-hsts-site-with-https-redirect-or-self-signed-site/19472

**Comment by asquelt** [comment]
side note: you might want to use DNS validation. it spared me a lot of headache with multiple load balancers, redirects, ie. it's trivial to write a hook if your dns provider allows you to add/remove RRs in programatic way (API, nsupdate).

**Comment by MAWane** [comment]
> If acmetool doesn't pass the configuration Let's Encrypt isn't going to either.

No, Boulder does not check cert validity while acmetool (incorrectly) does.

**Comment by hlandau** [comment]
Huh, I stand corrected. https://github.com/letsencrypt/boulder/blob/master/va/va.go#L198

This should be fixed so that acmetool has the same behaviour. Will fix.

**Comment by hlandau** [comment]
Fix is in v0.0.58.

**Comment by skinkie** [comment]
@hlandau I appreciate the effort. I have just upgraded acmetool per instructions for archlinux. But I am still seeing a failed test.

```
20160903164015 [DEBUG] acme.responder: http-01 self test
20160903164015 [INFO] acme.responder: http-01 self test failed: Get https://www.iepenbierferfier.frl/.well-known/acme-challenge/87UgC0CJ7o7CX2dKFPH-RrTpvP5AsZK06_erjRu0LSo: x509: certificate is valid for iepenbierferfier.frl, iepenbierferfier.nl, not www.iepenbierferfier.frl
20160903164015 [DEBUG] acme.responder: removing webroot file /var/run/acme/acme-challenge/87UgC0CJ7o7CX2dKFPH-RrTpvP5AsZK06_erjRu0LSo
20160903164015 [DEBUG] acme.responder: removing webroot file /opt/cherokee/var/www/.well-known/acme-challenge/87UgC0CJ7o7CX2dKFPH-RrTpvP5AsZK06_erjRu0LSo
```

**Comment by hlandau** [comment]
What's the output of `acmetool --version`?

**Comment by skinkie** [comment]
```
go version go1.7 linux/amd64 gc cgo=true
build unknown
```

I upgraded via:
```
cd acmetool-git
makepkg -s
sudo pacman -U ./acmetool*.pkg.tar.xz
```
Resulting in: acmetool-git-20160903-1-x86_64.pkg.tar.xz

**Comment by hlandau** [comment]
Please try the following:

1. `sudo pacman -R acmetool`
2. Run `which acmetool` and confirm that nothing is found.
3. Download https://github.com/hlandau/acme/releases/download/v0.0.58/acmetool-v0.0.58-linux_amd64_cgo.tar.gz and copy the `acmetool` binary inside to `/usr/local/bin/acmetool`
4. Determine if the problem persists. If it does, post `acmetool --version` output again.

**Comment by skinkie** [comment]
As reference, because it didn't work;
```
pacman -R acmetool-git
which acmetool
which: no acmetool in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

When executing ```acmetool want iepenbierferfier.frl www.iepenbierferfier.frl``` I don't get any output. I guess that may be as expected. After updating to the new certificate location www.iepenbierferfier.frl also works, which is awesome.

So I guess there might be details remaining for upgrading of acmetool for archlinux users. I guess if I had removed the entire folder, it would have fetch the new code from github.

**Comment by hlandau** [comment]
So this works now? Great.

Remember to remove the acmetool binary from `/usr/local/bin/acmetool` if you go back to using AUR. There have been issues where people switch from using the binary releases to using distro packaging, but `/usr/local/bin` takes priority, so they keep on using an old version unawares. You can always use `which acmetool` to confirm which binary you're using. (Note also that shells tend to cache the paths to binaries, so you may sometimes need to run `hash -r` in a shell to flush that cache or start a new shell.)

**Comment by infostreams** [comment]
I'm going to comment here (even though it's off-topic) for anyone coming here from Google. This is the top result when you search for `acme.storageops: could not obtain authorization for xxx: failed all combinations`, and none of the above helped me. 

Turns out I forgot something very basic (which was revealed by running acmetool with `--xlog.severity=debug`): acmetool was trying to start a server on port 443, and Nginx was already listening there. So it failed, and thus the certificate renewal failed, and therefore it gave me the above error. 

The solution is simple: temporarily switch off your webserver (e.g. `service nginx stop`), run acmetool, switch on your webserver (`service nginx start`). A better solution would obviously be to reconfigure acmetool to not start a server, but if you want a quick fix, this could be it. Hope it helps someone.

**Comment by hlandau** [comment]
@infostreams That's not really accurate. acmetool *tries* to listen on port 443, but if it fails this isn't a fatal error so long as it is able to provision the challenge another way. It's not intended that you should have to stop your webserver while invoking acmetool.

See the user guide for documentation as to how to configure challenges using a webroot, proxy, etc.

**Comment by infostreams** [comment]
You're right, obviously. I just ran into the same issue again today because I didn't follow up and adjust the configuration as I should have two months ago, and then was "helped" by my own answer from above. Guess it's time to solve this properly ;-)
